export const badge = {
  ".badge": {
    "--badge-color": "#fff",
    "--badge-bg": "transparent",
    "--badge-border-color": "#fff",
    display: "inline-flex",
    "align-items": "center",
    "justify-content": "center",
    "text-transform": "uppercase",
    "border-width": "1px",
    height: "-moz-fit-content",
    height: "fit-content",
    width: "-moz-fit-content",
    width: "fit-content",
    "font-size": "0.7rem",
    "padding-top": "2px",
    "padding-bottom": "2px",
    "padding-left": "0.563rem",
    "padding-right": "0.563rem",
    "border-radius": "100px",
    "background-color": "var(--badge-bg)",
    color: "var(--badge-color)",
    "border-color": "var(--badge-border-color)",
  },
  ".badge-primary": {
    "--badge-color": "var(--content-primary)",
    "--badge-bg": "rgb(var(--primary))",
    "--badge-border-color": "rgb(var(--primary))",
  },
  ".badge-secondary": {
    "--badge-color": "var(--content-secondary)",
    "--badge-bg": "rgb(var(--secondary))",
    "--badge-border-color": "rgb(var(--secondary))",
  },
  ".badge-accent": {
    "--badge-color": "var(--content-accent)",
    "--badge-bg": "rgb(var(--accent))",
    "--badge-border-color": "rgb(var(--accent))",
  },
  ".badge-light": {
    "--badge-color": "var(--content-light)",
    "--badge-bg": "rgb(var(--light))",
    "--badge-border-color": "rgb(var(--light))",
  },
  ".badge-info": {
    "--badge-color": "var(--content-info)",
    "--badge-bg": "rgb(var(--info))",
    "--badge-border-color": "rgb(var(--info))",
  },
  ".badge-success": {
    "--badge-color": "var(--content-success)",
    "--badge-bg": "rgb(var(--success))",
    "--badge-border-color": "rgb(var(--success))",
  },
  ".badge-warning": {
    "--badge-color": "var(--content-warning)",
    "--badge-bg": "rgb(var(--warning))",
    "--badge-border-color": "rgb(var(--warning))",
  },
  ".badge-error": {
    "--badge-color": "var(--content-error)",
    "--badge-bg": "rgb(var(--error))",
    "--badge-border-color": "rgb(var(--error))",
  },
  ".badge-outline": {
    "border-color": "var(--badge-bg)",
    "background-color": "transparent",
    color: "var(--badge-bg)",
  },
};
