export const button = {
  // Root Components
  // ".btn": {
  //   "--bs-btn-color": "#fff",
  //   "--bs-btn-bg": "rgb(var(--button))",
  //   "--bs-btn-border-color": "rgb(var(--button))",
  //   "--bs-btn-hover-bg": "rgba(var(--button), 0.5)",
  //   "--bs-btn-hover-border-color": "rgb(var(--button))",
  //   "text-transform": "uppercase",
  //   "border-width": "1px",
  //   "border-color": "var(--bs-btn-border-color)",
  //   height: "fit-content",
  //   "min-height": "2rem",
  //   "min-width": "5rem",
  //   width: "fit-content",
  //   "border-radius": "5px",
  //   "background-color": "var(--bs-btn-bg)",
  //   "font-weight": "500",
  //   "font-size": ".875rem",
  //   "line-height": "1.25rem",
  //   transition: "background 0.2s",
  //   color: "var(--bs-btn-color)",
  //   "padding-left": "1.25rem",
  //   "padding-right": "1.25rem",
  //   "padding-top": ".625rem",
  //   "padding-bottom": ".625rem",
  // },
  ".badge": {
    "--bs-badge-color": "#fff",
    "--bs-badge-bg": "transparent",
    "--bs-badge-border-color": "#fff",
    "text-transform": "uppercase",
    "border-width": "1px",
    height: "fit-content",
    width: "fit-content",
    height: "-moz-fit-content",
    width: "-moz-fit-content",
    "font-size": "0.7rem",
    "padding-top": "2px",
    "padding-bottom": "2px",
    "padding-left": "0.563rem",
    "padding-right": "0.563rem",
    "border-radius": "100px",
    "background-color": "var(--bs-badge-bg)",
    color: "var(--bs-badge-color)",
    "border-color": "var(--bs-badge-border-color)",
  },
  // End Root Components
  // ".btn:hover": {
  //   "background-color": "var(--bs-btn-hover-bg)",
  //   transition: "background 0.3s",
  //   "border-color": "rgba(var(--primary), 0.5)",
  // },
  // ".btn:active": {
  //   transform: "scale(90%)",
  //   transition: "background, transform 0.2s",
  // },
  // Button Colors
  // ".btn-primary": {
  //   "--bs-btn-color": "#fff",
  //   "--bs-btn-bg": "rgb(var(--primary))",
  //   "--bs-btn-border-color": "rgb(var(--primary))",
  //   "--bs-btn-hover-bg": "rgba(var(--primary), 0.5)",
  //   "--bs-btn-hover-border-color": "rgba(var(--primary), 0.5)",
  // },
  // ".btn-secondary": {
  //   "--bs-btn-color": "#fff",
  //   "--bs-btn-bg": "rgb(var(--secondary))",
  //   "--bs-btn-border-color": "rgb(var(--secondary))",
  //   "--bs-btn-hover-bg": "rgba(var(--secondary), 0.5)",
  //   "--bs-btn-hover-border-color": "rgb(var(--secondary))",
  // },
  // ".btn-accent": {
  //   "--bs-btn-color": "#fff",
  //   "--bs-btn-bg": "rgb(var(--accent))",
  //   "--bs-btn-border-color": "rgb(var(--accent))",
  //   "--bs-btn-hover-bg": "rgba(var(--accent), 0.5)",
  //   "--bs-btn-hover-border-color": "rgb(var(--accent))",
  // },
  // ".btn-success": {
  //   "--bs-btn-color": "#161618",
  //   "--bs-btn-bg": "rgb(var(--success))",
  //   "--bs-btn-border-color": "rgb(var(--success))",
  //   "--bs-btn-hover-bg": "rgba(var(--success), 0.5)",
  //   "--bs-btn-hover-border-color": "rgb(var(--success))",
  // },
  // ".btn-info": {
  //   "--bs-btn-color": "#161618",
  //   "--bs-btn-bg": "rgb(var(--info))",
  //   "--bs-btn-border-color": "rgb(var(--info))",
  //   "--bs-btn-hover-bg": "rgba(var(--info), 0.5)",
  //   "--bs-btn-hover-border-color": "rgb(var(--info))",
  // },
  // ".btn-warning": {
  //   "--bs-btn-color": "#161618",
  //   "--bs-btn-bg": "rgb(var(--warning))",
  //   "--bs-btn-border-color": "rgb(var(--warning))",
  //   "--bs-btn-hover-bg": "rgba(var(--warning), 0.5)",
  //   "--bs-btn-hover-border-color": "rgb(var(--warning))",
  // },
  // ".btn-error": {
  //   "--bs-btn-color": "#161618",
  //   "--bs-btn-bg": "rgb(var(--error))",
  //   "--bs-btn-border-color": "rgb(var(--error))",
  //   "--bs-btn-hover-bg": "rgba(var(--error), 0.5)",
  //   "--bs-btn-hover-border-color": "rgb(var(--error))",
  // },
  // ".btn-light": {
  //   "--bs-btn-color": "#161618",
  //   "--bs-btn-bg": "rgb(var(--light))",
  //   "--bs-btn-border-color": "rgb(var(--light))",
  //   "--bs-btn-hover-bg": "rgba(var(--light), 0.5)",
  //   "--bs-btn-hover-border-color": "rgb(var(--light))",
  // },
  // End Button Color
  // Badge Color
  ".badge-primary": {
    "--bs-badge-color": "#fff",
    "--bs-badge-bg": "rgb(var(--primary))",
    "--bs-badge-border-color": "rgb(var(--primary))",
  },
  ".badge-secondary": {
    "--bs-badge-color": "#fff",
    "--bs-badge-bg": "rgb(var(--secondary))",
    "--bs-badge-border-color": "rgb(var(--secondary))",
  },
  ".badge-accent": {
    "--bs-badge-color": "#fff",
    "--bs-badge-bg": "rgb(var(--accent))",
    "--bs-badge-border-color": "rgb(var(--accent))",
  },
  ".badge-light": {
    "--bs-badge-color": "#161618",
    "--bs-badge-bg": "rgb(var(--light))",
    "--bs-badge-border-color": "rgb(var(--light))",
  },
  ".badge-info": {
    "--bs-badge-color": "#fff",
    "--bs-badge-bg": "rgb(var(--info))",
    "--bs-badge-border-color": "rgb(var(--info))",
  },
  ".badge-success": {
    "--bs-badge-color": "#fff",
    "--bs-badge-bg": "rgb(var(--success))",
    "--bs-badge-border-color": "rgb(var(--success))",
  },
  ".badge-warning": {
    "--bs-badge-color": "#fff",
    "--bs-badge-bg": "rgb(var(--warning))",
    "--bs-badge-border-color": "rgb(var(--warning))",
  },
  ".badge-error": {
    "--bs-badge-color": "#fff",
    "--bs-badge-bg": "rgb(var(--error))",
    "--bs-badge-border-color": "rgb(var(--error))",
  },
  // End Badge Color
  // Additional
  // ".btn-outline": {
  //   "border-color": "var(--bs-btn-bg)",
  //   "background-color": "transparent",
  //   color: "var(--bs-btn-bg)",
  // },
  // ".btn-lg": {
  //   "padding-left": "1.5rem",
  //   "padding-right": "1.5rem",
  //   "min-height": "3.5rem",
  //   "font-size": "1.125rem",
  // },
  // ".btn-sm": {
  //   "padding-left": "1rem",
  //   "padding-right": "1rem",
  //   "min-width": "4rem",
  //   "min-height": "1.25rem",
  //   "font-size": "11px",
  // },
  // ".btn-wide": {
  //   "min-width": "16rem",
  // },
  ".badge-outline": {
    "border-color": "var(--bs-badge-bg)",
    "background-color": "transparent",
    color: "var(--bs-badge-bg)",
  },
};
