import plugin from "tailwindcss/plugin";
import { base } from "./base";
import { button } from "./button";
import { color } from "./color";
import { navbar } from "./navbar";
import { alert } from "./alert";
import { badge } from "./badge";
import { card } from "./card";
import { progress } from "./progress";
import { dropdown } from "./dropdown";
import { table } from "./table";
import { hero } from "./hero";
import { footer } from "./footer";
import { input } from "./input";
import { select } from "./select";
import { additional } from "./additional";
import { toggle } from "./toggle";

export default plugin(({ addBase, addComponents, theme, addUtilities }) => {
  addBase(base);
  addUtilities(color, ["responsive", "hover"]);
  addComponents(additional);
  addComponents(button);
  addComponents(navbar);
  addComponents(alert);
  addComponents(badge);
  addComponents(card);
  addComponents(progress);
  addComponents(dropdown);
  addComponents(table);
  addComponents(hero);
  addComponents(footer);
  addComponents(input);
  addComponents(select);
  addComponents(toggle);
});
