export const select = {
  ".select": {
    "--select-border-opacity": "1",
    "--select-border-width": "0px",
    "--select-border-color": "transparent",
    "--select-bg": "transparent",
    display: "inline-flex",
    cursor: "pointer",
    "-webkit-user-select": "none",
    "user-select": "none",
    "-webkit-appearance": "none",
    "-moz-appearance": "none",
    appearance: "none",
    height: "3rem",
    "padding-left": "1rem",
    "padding-right": "2.5rem",
    "font-size": "0.875rem",
    "line-height": "1.25rem",
    "min-height": "3rem",
    "border-width": "var(--select-border-width)",
    "border-color": "var(--select-border-color)",
    "background-color": "var(--select-bg)",
    "border-radius": "0.5rem",
    "background-image":
      "linear-gradient(45deg, transparent 50%, currentColor 50%), linear-gradient(135deg, currentColor 50%, transparent 50%)",
    "background-position":
      "calc(100% - 20px) calc(1px + 50%), calc(100% - 16.1px) calc(1px + 50%)",
    "background-size": "4px 4px, 4px 4px",
    "background-repeat": "no-repeat",
  },
  ".select:focus": {
    "outline-style": "solid",
    "outline-width": "2px",
    "outline-offset": "2px",
    "outline-color": "rgba(0, 0, 0, 0.2)",
  },
  ".select-bordered": {
    "--select-border-opacity": "1",
    "--select-border-width": "1px",
    "--select-border-color": "gray",
    "--select-bg": "transparent",
  },
  ".select-primary": {
    "--select-border-opacity": "1",
    "--select-border-width": "1px",
    "--select-border-color": "rgb(var(--primary))",
    "--select-bg": "transparent",
  },
  ".select.select-primary:focus": {
    "outline-style": "solid",
    "outline-width": "2px",
    "outline-offset": "2px",
    "outline-color": "rgba(var(--primary), 0.2)",
  },
  ".select-secondary": {
    "--select-border-opacity": "1",
    "--select-border-width": "1px",
    "--select-border-color": "rgb(var(--secondary))",
    "--select-bg": "transparent",
  },
  ".select.select-secondary:focus": {
    "outline-style": "solid",
    "outline-width": "2px",
    "outline-offset": "2px",
    "outline-color": "rgba(var(--secondary), 0.2)",
  },
  ".select-accent": {
    "--select-border-opacity": "1",
    "--select-border-width": "1px",
    "--select-border-color": "rgb(var(--accent))",
    "--select-bg": "transparent",
  },
  ".select.select-accent:focus": {
    "outline-style": "solid",
    "outline-width": "2px",
    "outline-offset": "2px",
    "outline-color": "rgba(var(--accent), 0.2)",
  },
  ".select-info": {
    "--select-border-opacity": "1",
    "--select-border-width": "1px",
    "--select-border-color": "rgb(var(--info))",
    "--select-bg": "transparent",
  },
  ".select.select-info:focus": {
    "outline-style": "solid",
    "outline-width": "2px",
    "outline-offset": "2px",
    "outline-color": "rgba(var(--info), 0.2)",
  },
  ".select-success": {
    "--select-border-opacity": "1",
    "--select-border-width": "1px",
    "--select-border-color": "rgb(var(--success))",
    "--select-bg": "transparent",
  },
  ".select.select-success:focus": {
    "outline-style": "solid",
    "outline-width": "2px",
    "outline-offset": "2px",
    "outline-color": "rgba(var(--success), 0.2)",
  },
  ".select-warning": {
    "--select-border-opacity": "1",
    "--select-border-width": "1px",
    "--select-border-color": "rgb(var(--warning))",
    "--select-bg": "transparent",
  },
  ".select.select-warning:focus": {
    "outline-style": "solid",
    "outline-width": "2px",
    "outline-offset": "2px",
    "outline-color": "rgba(var(--warning), 0.2)",
  },
  ".select-error": {
    "--select-border-opacity": "1",
    "--select-border-width": "1px",
    "--select-border-color": "rgb(var(--error))",
    "--select-bg": "transparent",
  },
  ".select.select-error:focus": {
    "outline-style": "solid",
    "outline-width": "2px",
    "outline-offset": "2px",
    "outline-color": "rgba(var(--error), 0.2)",
  },
};
